---
# {PLAYER} = Name of the player that finished the quest. ONLY WORKS ON REWARDS
# {QUEST} = Name of the quest. Only where they are!
# Types : move, breakblock, placeblock, kills

category-select-title: "§l§iQuests"
category-select-content: "Please select a category"
quest-select-content: "Please choose a quest"
finished-quest-message: "§7You finished the quest §6{QUEST}"
button-leave: "Leave"
button-info-start: "Start the quest"
button-info-pause: "Stop the quest"
quest-already-finished: "§cYou have already finished this quest!"
paused-quest: "§7You stopped the quest §6{QUEST}"
started-quest: "§7You started the quest §6{QUEST}"
quest-opened: "Not started"
quest-inprogress: "Current quest"
quest-finished: "Completed"

categories:
  General: # Category Name
    Lumberjack: # Quest Name (config only)
      name: "Example 1" # Quest Name (in-game)
      description: "Break 75 Stone" # Description
      type: breakblock # Type
      block: "1" # Block they need to break/place/etc
      number: 75 # Number of blocks they need to break/place/etc
      rewards: # Rewards are given by commands, you can give anything rank by a command
        - "givemoney 1200 {PLAYER}"
    Voyager: # Second Quest under General Category, you can add unlimited
      name: "Voyager"
      description: "Move 100 blocks"
      type: move
      number: 100
      rewards:
        - "givemoney 1800 {PLAYER}"
  Placing: # Second Category, however you can add unlimited
    Placing:
      name: "Block Placing"
      description: "Place 55 wood"
      type: placeblock
      block: "17"
      number: 55
      rewards:
        - "give {PLAYER} dirt 64"
    Kill:
      name: "Killer"
      description: "Kill 25 players"
      type: kills
      number: 25
      rewards:
        - "givemoney 2800{PLAYER}"
...
